include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  COMPOSER: composer.json
  COMPOSER_ROOT_VERSION: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}${CI_COMMIT_BRANCH}-dev"

stages:
  - 🏗️ Build
  - 🪄 Lint
  - 🗜️ Test

.default-job-settings: &default-job-settings
  interruptible: true
  allow_failure: false
  variables:
    _TARGET_PHP: "8.3"
    _TARGET_DB: "sqlite-3"
  image:
    name: $_CONFIG_DOCKERHUB_ROOT/php-$_TARGET_PHP-apache:production
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.default-job-settings-lint: &default-job-settings-lint
  <<: *default-job-settings
  variables:
    _TARGET_PHP: "8.3"
    _TARGET_DB: "sqlite-3"

# Cache configuration
.cache-composer: &cache-composer
  cache:
    key:
      files:
        - composer.json
        - composer.lock
    paths:
      - vendor/

.cache-yarn: &cache-yarn
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/

# Build stage jobs
'📦️ Composer':
  <<: *default-job-settings
  <<: *cache-composer
  stage: 🏗️ Build
  script:
    - composer install --optimize-autoloader

'📦️ Yarn':
  <<: *default-job-settings
  <<: *cache-yarn
  stage: 🏗️ Build
  script:
    - yarn install

# Lint stage jobs
'🧹 PHP Coding standards (PHPCS)':
  <<: *default-job-settings-lint
  <<: *cache-composer
  stage: 🪄 Lint
  script:
    - composer install --optimize-autoloader
    - vendor/bin/phpcs

'🧹 PHP Static Analysis (phpstan)':
  <<: *default-job-settings-lint
  <<: *cache-composer
  stage: 🪄 Lint
  script:
    - composer install --optimize-autoloader
    - vendor/bin/phpstan analyse
  allow_failure: true

# Test stage jobs
'PHP 8.3 MySQL 8':
  <<: *default-job-settings
  stage: 🗜️ Test
  variables:
    _TARGET_PHP: "8.3"
    _TARGET_DB: "mysql-8"
  image:
    name: $_CONFIG_DOCKERHUB_ROOT/php-$_TARGET_PHP-apache:production

'PHP 8.4 MySQL 8':
  <<: *default-job-settings
  stage: 🗜️ Test
  variables:
    _TARGET_PHP: "8.4"
    _TARGET_DB: "mysql-8"
  image:
    name: $_CONFIG_DOCKERHUB_ROOT/php-$_TARGET_PHP-apache:production